### ISSUE TITLE
Complete lack of license

### ISSUE THREAD

**Issue by coolo** [harrowio/capistrano-harrow#2]
Trying to package the gem (to please capistrano's requirements) for openSUSE, I wonder what the license is. Neither this repo nor the gem have any kind of open source license.

**Comment by leehambley** [comment]
You can assume MIT, I'll upload a license soon.

Might I ask, why is it necessary to package already packaged systems when the Ruby language has it's own package manager? I tend to avoid OS level packages like the plague, and most Ruby developers seem to do the same. 

I'm sure packaging things for an OS is quite the thankless task, so please don't misunderstand my curiosity.

**Comment by coolo** [comment]
For ones: we can verify the packages our users rely on have open source licenses :)

The packaging of gems is 99% automated and we use the generated packages to be able to build appliances without having to rely on external infrastructure. So the target users aren't really ruby developers.

**Comment by md5** [comment]
To @coolo and all others who are interested, I've opened https://github.com/harrowio/capistrano-harrow/pull/3 to get the license added to the `capistrano-harrow.gemspec` file as well to ease automated checking.
